export const ADD_STUDENT_REQUESTED = 'ADD_STUDENT_REQUESTED';
export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_ERROR = 'ADD_STUDENT_ERROR';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
